apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: elnidala/repo-frontend:latest 
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://192.168.49.2:30737/api/tasks"  #replace the ip of your server and nodeport of the nginx-service
        ports:
        - containerPort: 3000